services:
  api:
    build: .
    env_file: .env
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      piston:
        condition: service_started
    restart: unless-stopped

  piston:
    image: ghcr.io/engineer-man/piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston_data:/piston
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d codeplatform"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  piston_data:
